name: Pre-release CI

on:
  workflow_run:
    workflows: [Quality Checks]
    types:
      - completed

jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18, 20, 22]
    steps:
      - uses: actions/checkout@v4
      - name: Common Setup Node ${{ matrix.node-version }} and pnpm
        uses: ./.github/actions/common-setup
        with:
          pnpm-version: 10.2.0
          node-version: ${{ matrix.node-version }}
          cache: pnpm

      - name: Build
        run: |
          pnpm install --frozen-lockfile --prefer-offline
          pnpm run build
        env:
          CI: true

  dry-run-pack:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Common Setup
        uses: ./.github/actions/common-setup
        with:
          pnpm-version: 10.2.0
          node-version: 22
          cache: pnpm

      - run: pnpm install --frozen-lockfile --prefer-offline
      - run: pnpm run build
      - run: pnpm pack --dry-run
